SELECT LOWER('abCdeF') from dual;
select upper('abCdeF') from dual;
select initcap('abCdeF') from dual;
select hobby, lpad(hobby,20,'~') from temp;
select hobby, rpad(hobby,20,'~') from temp;
SELECT SUBSTRB(HOBBY,1,2) FROM TEMP;

SELECT LENGTHB('한') FROM DUAL;

SELECT TEL, INSTR(TEL,'9') FROM TEMP;

SELECT TEL, LTRIM(TEL,'010') FROM TEMP;

SELECT TEL, RTRIM(TEL,'010') FROM TEMP;

SELECT TEL, TRANSLATE(TEL, '019','*!~') FROM TEMP;

SELECT TEL, REPLACE(TEL, '010','***') FROM TEMP;

SELECT ROUND(11234.5678) FROM DUAL;

SELECT ROUND(11234.5678,1) FROM DUAL;

SELECT ROUND(11234.5678,-2) FROM DUAL;

SELECT ROUND(11234.5678) FROM DUAL;

SELECT ROUND(11234.5678,1) FROM DUAL;

SELECT TRUNC(11234.5678) FROM DUAL;

SELECT TRUNC(11234.5678,1) FROM DUAL;

SELECT TRUNC(11234.5678,-2) FROM DUAL;

SELECT CEIL(4.5678) FROM DUAL;

SELECT FLOOR(4.5678) FROM DUAL;

SELECT SQRT(4) FROM DUAL;

SELECT ABS(-10) FROM DUAL;

SELECT MOD(10,3) FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, -1) FROM DUAL;

SELECT NEXT_DAY(SYSDATE,2) FROM DUAL;

SELECT ROUND(SYSDATE, 'YYYY') FROM DUAL;

SELECT ROUND(SYSDATE, 'MM') FROM DUAL;

SELECT TO_CHAR(ROUND(SYSDATE,'DD'), 'YYYY/MM/DD HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(ROUND(SYSDATE,'HH'), 'YYYY/MM/DD HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(ROUND(SYSDATE,'MI'), 'YYYY/MM/DD HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(ROUND(BIRTH_DATE, 'MI'), 'YYYY/MM/DD HH24MISS') FROM TEMP;

SELECT TRUNC(SYSDATE, 'YYYY') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYMMDD HH24MISS') FROM DUAL;'

SELECT TO_CHAR(BIRTH_DATE, 'YYYYMMDD HH24MISS') FROM TEMP;

SELECT TO_CHAR(SYSDATE, 'DAY') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MON') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'MONTH') FROM DUAL;

SELECT TO_CHAR(SYSTIMESTAMP,'YYYYMMDD HH24MISS FF3') FROM DUAL;

SELECT TO_CHAR(01234) || 'A' FROM DUAL;

SELECT 01234 || 'A' FROM DUAL;

SELECT TO_NUMBER('12345') FROM DUAL;

SELECT TO_NUMBER('12345A') FROM DUAL;

SELECT TO_DATE('2020 01 02 13:20:31','YYYY MM DD HH24:MI:SS') FROM DUAL;

SELECT GREATEST(1,2,3,4,5) FROM DUAL;

SELECT GREATEST('10','2') FROM DUAL;

SELECT GREATEST('10',2) FROM DUAL;

SELECT GREATEST(2,'10') FROM DUAL;

SELECT LEAST(1,2,3,4,5) FROM DUAL;

SELECT LEAST('10','2') FROM DUAL;

SELECT LEAST('10',2) FROM DUAL;

SELECT LEAST(2,'10') FROM DUAL;

SELECT VSIZE('한글') FROM DUAL;

SELECT VSIZE(CONVERT('한글','K016MSWIN949')) FROM DUAL;

SELECT AVG(SALARY) FROM TEMP;

SELECT AVG(SALARY),COUNT(SALARY),COUNT(HOBBY), COUNT(*) FROM TEMP;

SELECT MIN(SALARY), MAX(SALARY), SUM(SALARY), STDDEV(SALARY), VARIANCE(SALARY) FROM TEMP;

SELECT MIN(SALARY), MAX(SALARY), MIN(EMP_NAME), MAX(EMP_NAME), SUM(SALARY), STDDEV(SALARY), VARIANCE(SALARY), CORR(SALARY,EMP_ID) FROM TEMP;